name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]  # Using your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Python version
        run: python3 --version

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run Python script
        run: |
          python3 app.py
          
      - name: Create Artifact
        run: |
          mkdir -p output
          cp app.py output/

      - name: List files in output directory
        run: ls -l output/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: output/
